apiVersion: v1
kind: Template
labels:
  template: secrets-template
message: |-
  For more information about using this template, including OpenShift considerations, see the documentation (TODO).
metadata:
  annotations:
    description: |-
      This templates performs the basic setup for applications.
    iconClass: icon-nodejs
    openshift.io/display-name: Component Template
    template.openshift.io/long-description: This template defines resources needed
      to develop an application, including a build configuration, application
      deployment configuration.
  name: secrets
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: cd-user-token
  type: kubernetes.io/basic-auth
  data:
    password: ${CD_USER_PWD}
    ca.crt: ${BITBUCKET_CA_BUNDLE}
parameters:
- description: The name of the application project.
  displayName: Application
  name: PROJECT
  required: true
- description: Base64 encoded password of the cd_user
  displayName: Base64 encoded password of the cd_user
  name: CD_USER_PWD
  value: CD_USER_PWD
- description: Base64 encoded CA bundle of the bitbucket server
  displayName: Base64 encoded CA bundle of the bitbucket server
  name: BITBUCKET_CA_BUNDLE
  value: BITBUCKET_CA_BUNDLE
